{\rtf1\ansi\ansicpg1252\cocoartf2511
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red25\green55\blue116;\red244\green244\blue244;\red0\green0\blue0;
\red25\green28\blue31;}
{\*\expandedcolortbl;;\cssrgb\c12549\c29020\c52941;\cssrgb\c96471\c96471\c96471;\cssrgb\c0\c0\c0;
\cssrgb\c12941\c14510\c16078;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl432\partightenfactor0

\f0\fs28\fsmilli14400 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 application\cf4 \strokec4 :\cf5 \strokec5  \cf2 \strokec2 hello\cf5 \strokec5 \
\cf2 \strokec2 version\cf4 \strokec4 :\cf5 \strokec5  \cf2 \strokec2 1\cf5 \strokec5 \
\cf2 \strokec2 runtime\cf4 \strokec4 :\cf5 \strokec5  \cf2 \strokec2 python27\cf5 \strokec5 \
\cf2 \strokec2 api_version\cf4 \strokec4 :\cf5 \strokec5  \cf2 \strokec2 1\cf5 \strokec5 \
\cf2 \strokec2 threadsafe\cf4 \strokec4 :\cf5 \strokec5  \cf2 \strokec2 false\cf5 \strokec5 \
\cf2 \strokec2 handlers\cf4 \strokec4 :\cf5 \strokec5 \
\pard\pardeftab720\sl432\partightenfactor0
\cf4 \strokec4 -\cf5 \strokec5  \cf2 \strokec2 url\cf4 \strokec4 :\cf5 \strokec5  \cf2 \strokec2 /.*\cf5 \strokec5 \
  \cf2 \strokec2 script\cf4 \strokec4 :\cf5 \strokec5  \cf2 \strokec2 hello.py}